In [1]:
function knapsack(weights,values,items,capacity)
    if(items==0 || capacity==0)
        return 0
    end
    if(weights[items]>capacity)
        return knapsack(weights,values,items-1,capacity)
    end
    return max(knapsack(weights,values,items-1,capacity-weights[items])+values[items],knapsack(weights,values,items-1,capacity))
end

knapsack (generic function with 1 method)

In [2]:
weights=[10,20,30]

3-element Array{Int64,1}:
 10
 20
 30

In [4]:
values=[60,100,120]
capacity=50
items=3

3

In [5]:
knapsack(weights,values,items,capacity)

220

In [1]:
print("Hi")

Hi

# Knap Sack 1/0

In [2]:
function knapsack(weights, values, items, capacity)
    if (items == 0 || capacity == 0)
        return 0
    end
    if (weights[items] > capacity)
        return knapsack(weights, values, items - 1, capacity)
    end
    return max(
        knapsack(weights, values, items - 1, capacity - weights[items]) + values[items],
        knapsack(weights, values, items - 1, capacity),
    )
end

println("Enter the number of items")
n = readline()
n = parse(Int64, n)
println("Enter the capacity of the knapsack")
w = readline()
w = parse(Int64, w)
values = Int64[]
println("Enter the values of each item")
for i = 1:n
    temp = readline()
    temp = parse(Int64, temp)
    push!(values, temp)
end
weights = Int64[]
println("Enter the weights of each item")
for i = 1:n
    temp = readline()
    temp = parse(Int64, temp)
    push!(weights, temp)
end
print(knapsack(weights, values, n, w))



Enter the number of items
stdin> 3
Enter the capacity of the knapsack
stdin> 50
Enter the values of each item
stdin> 60
stdin> 100
stdin> 120
Enter the weights of each item
stdin> 10
stdin> 20
stdin> 30
220

# Rainwater trapping

In [4]:
println("Enter the length of array!")
n = readline()
n = parse(Int64,n)
array = Int64[]
println("Enter the array !")
for i in 1:n
    temp=readline()
    temp=parse(Int64,temp)
    push!(array,temp)
end

Enter the length of array!
stdin> 3
Enter the array !
stdin> 2
stdin> 0
stdin> 2


In [48]:
function rainWater(n,array)
    left=zeros(n)
left[1]=array[1]
for i in 2:n
    left[i]=max(left[i-1],array[i])
end
right=zeros(n)
right[n]=array[n]
for i in n-1:-1:1
    right[i]=max(right[i+1],array[i])
end
total=0
for i in 1:n
    total+=min(left[i],right[i])-array[i]
end
return total
end


rainWater (generic function with 1 method)

In [49]:
array

3-element Array{Int64,1}:
 2
 0
 2

In [47]:
left=zeros(n)
left[1]=array[1]
for i in 2:n
    left[i]=max(left[i-1],array[i])
end
right=zeros(n)
right[n]=array[n]
for i in n-1:-1:1
    right[i]=max(right[i+1],array[i])
end
total=0
for i in 1:n
    total+=min(left[i],right[i])-array[i]
end
total

2.0

In [46]:
print(left)
print(right)

[2.0, 2.0, 2.0][2.0, 2.0, 2.0]

In [50]:
rainWater(n,array)

2.0

# Tower of Hanoi

In [61]:
function towerOfHanoi(discs,source,destination,helper)
    if(discs==0)
        return 
    end
    towerOfHanoi(discs-1,source,helper,destination)
    println("Move from $(source) to $(destination)")
    towerOfHanoi(discs-1,helper,destination,source)
end

towerOfHanoi (generic function with 1 method)

In [62]:
towerOfHanoi(3,"A","B","C")

Move from A to B
Move from A to C
Move from B to C
Move from A to B
Move from C to A
Move from C to B
Move from A to B


# Coin Change DP 

In [111]:
println("Enter the coin change you want ")
n =readline()
n=parse(Int64,n)
println("Enter the number of coins ")
N=readline()
N=parse(Int64,N)
println("Enter the values of the coins ")
coins=Int64[]
for i in 1:N
    temp=readline()
    temp=parse(Int64,temp)
    push!(coins,temp)
end

Enter the coin change you want 
stdin> 20
Enter the number of coins 
stdin> 3
Enter the values of the coins 
stdin> 7
stdin> 5
stdin> 1


In [148]:
function minCoins(n,arr,dp)
    if(n==0)
        return 0
    end
    ans=typemax(Int64)
    for i in 1:size(arr)[1]
        if(n-arr[i]>=0)
            subans=0
            if(dp[n-arr[i]] != -1)
                subans=dp[n-arr[i]]
            else
                subans=minCoins(n-arr[i],arr,dp)
            end
            if(subans!=typemax(Int64) && subans+1<ans)
                ans=subans+1
            end
        end
        
    end
    dp[n]=ans
    return ans
end

minCoins (generic function with 1 method)

In [156]:

dp=OffsetArray{Float64}(-1.0,0:1000)
minCoins(n,coins,dp)

LoadError: MethodError: no method matching OffsetArray{Float64,N,AA} where AA<:AbstractArray{Float64,N} where N(::Float64, ::UnitRange{Int64})
Closest candidates are:
  OffsetArray{Float64,N,AA} where AA<:AbstractArray{Float64,N} where N(!Matched::Union{Missing, Nothing, UndefInitializer}, ::Any...) where T at C:\Users\Prashant\.julia\packages\OffsetArrays\lli7H\src\OffsetArrays.jl:215

In [127]:
n

20

In [107]:
coins

3-element Array{Int64,1}:
 1
 2
 3

In [151]:
dp=OffsetArray{Float64}(1,0:1000)

LoadError: MethodError: no method matching OffsetArray{Float64,N,AA} where AA<:AbstractArray{Float64,N} where N(::Int64, ::UnitRange{Int64})
Closest candidates are:
  OffsetArray{Float64,N,AA} where AA<:AbstractArray{Float64,N} where N(!Matched::Union{Missing, Nothing, UndefInitializer}, ::Any...) where T at C:\Users\Prashant\.julia\packages\OffsetArrays\lli7H\src\OffsetArrays.jl:215

In [140]:
using OffsetArrays


┌ Info: Precompiling OffsetArrays [6fe1bfb0-de20-5000-8ca7-80f57d26f881]
└ @ Base loading.jl:1278


1001-element OffsetArray(::Array{Float64,1}, 0:1000) with eltype Float64 with indices 0:1000:
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  ⋮
 -2.028136923161858e180
  1.1769372777e-314
  0.0
 -3.7517015576001196e-298
  0.0
 -3.7517106324804154e-298
  0.0
  4.912221034e-315
  7.4072513706462e-309
  3.524526216e-315

In [143]:
dp[0]

0.0

In [144]:
dp[1]

0.0